# from gymnasium_env.envs.simple_robot import SimpleRobotEnv
# from gymnasium_env.envs.simple_robot_sine import SimpleRobotEnvSine
# from gymnasium_env.envs.simple_mujoco import SimpleMujocoEnv
# from gymnasium_env.envs.ur5e_2f85_mujoco_env import ur5e_2f85Env
from gymnasium_env.envs.ur5e_2f85_pybullet_env_simple_1a1 import ur5e_2f85_pybulletEnv_Simple_1a1
from gymnasium_env.envs.ur5e_2f85_pybullet_env_simple_1a2 import ur5e_2f85_pybulletEnv_Simple_1a2
from gymnasium_env.envs.ur5e_2f85_pybullet_env_simple_1a3 import ur5e_2f85_pybulletEnv_Simple_1a3
from gymnasium_env.envs.ur5e_pybullet_env_1a4 import ur5e_pybulletEnv_1a4
from gymnasium_env.envs.ur5e_pybullet_env_1a5 import ur5e_pybulletEnv_1a5

from gymnasium_env.envs.ur5e_pybullet_env_1b1 import ur5e_pybulletEnv_1b1
from gymnasium_env.envs.ur5e_pybullet_env_1b2 import ur5e_pybulletEnv_1b2

from gymnasium_env.envs.ur5e_2f85_pybullet_env_2a import ur5e_2f85_pybulletEnv_2a
from gymnasium_env.envs.ur5e_2f85_pybullet_env_2b import ur5e_2f85_pybulletEnv_2b
from gymnasium_env.envs.ur5e_2f85_pybullet_env_2c import ur5e_2f85_pybulletEnv_2c
from gymnasium_env.envs.ur5e_2f85_pybullet_env_2d import ur5e_2f85_pybulletEnv_2d

# Other simulations
from gymnasium_env.envs.ur5e_pybullet_random_orient_env import ur5e_pybulletEnv_random_orient
from gymnasium_env.envs.ur5e_2f85_digit_pybullet_env import ur5e_2f85_pybulletEnv_digit
from gymnasium_env.envs.ur5e_pybullet_env_lowfreq import ur5e_pybulletEnv_lowfreq